name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_gpa_calculation
      id: test_gpa_calculation
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_gpa_calculation
        setup-command: sudo -H pip3 install pytest
        command: pytest -k test_gpa_calculation
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_GPA_CALCULATION_RESULTS: "${{steps.test_gpa_calculation.outputs.result}}"
      with:
        runners: test_gpa_calculation
